### ISSUE TITLE
博客系统挂了

### ISSUE THREAD

**Issue by HapCoderWei** [andelf/andelf.github.io#1]
你好,哥们,你的博客系统好像坏了,不能从网上直接访问了.我想要看你写的树莓派和homekit的文章,它在谷歌中排名很高,但是打不开了,你能修复一下你的博客吗?谢谢

**Comment by andelf** [comment]
http://andelf.github.io/blog/2016/09/16/play-homekit-with-ios-10-and-raspberry-pi/

可以访问。

2017-04-11 22:35 GMT+08:00 HapCoderWei <notifications@github.com>:

**Comment by andelf** [comment]
源码地址：

https://github.com/andelf/andelf.github.io/blob/source/source/_posts/2016-09-16-play-homekit-with-ios-10-and-raspberry-pi.markdown

**Comment by HapCoderWei** [comment]
好的,已经可以正常访问了,谢谢
